### ISSUE TITLE
 Outline a proposal for how open demographics might accelerate D&I standards for data& metrics in Open Source through CHAOSS(or other partner) implementation

### ISSUE THREAD

**Issue by emmairwin** [OSdiversity/osdiversity#1]
A proposal might have(based on brainstorming)

- [x] What Open Demographics is now
- [x] What the potential is 
- [ ] How it can bring value to Open Source through CHAOSS
- [ ] What an experiment might be we can run through CHAOSS with an existing Open Communities data 
(Out of scope: which community that might be, even if we have some ideas)

**Comment by drnikko** [comment]
Just want to update that I sent out Open Demographics for review to ~5 people on twitter (and then everyone on twitter), and will be asking, more broadly, for general feedback on the content and quality of the questions as they currently stand.

There are a fair number of obvious shortcomings that will need to be addressed  - the biggest is that it's US-centric and doesn't even extend to North America - but those will be addressed in coming iterations.

**Comment by emmairwin** [comment]
Adding link :  https://drnikki.github.io/open-demographics/
